---
abstract: 'tie Amazon S3 buckets to Perl hashes'
author:
  - 'Zak B. Elep <zakame@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.71'
license: MIT
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Tie-Amazon-S3
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Net::Amazon::S3: 0
version: 0.03_02
